root: true
env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
  project:
    - "./tsconfig.json"
plugins:
  - '@typescript-eslint'
rules: {}
